Backport non-breaking changes from v1.0 to v0.2.x
rust-embedded/embedded-hal pull request #301
Opened 2021-07-31 05:49 UTC by burrbull

2021-07-31 05:49 UTC, rust-highfive commented
r? @ryankurte

(rust-highfive has picked a reviewer for you, use r? to override)

2021-07-31 05:49 UTC, rust-highfive commented
:warning: **Warning** :warning:

* Pull requests are usually filed against the master branch for this repo, but this one is against v0.2.x. Please double check that you specified the right target!

2021-08-01 07:17 UTC, eldruin requested changes
Seems like a good idea to me. Could you also add entries to the changelog about this? You can probably copy-paste them.

2021-08-01 08:38 UTC, burrbull commented
> Could you also add entries to the changelog about this?

Done

2021-08-01 09:46 UTC, eldruin approved these changes
Looks good to me, thank you!

bors r+

2021-08-01 09:47 UTC, merged